#!/usr/bin/env python
# coding: utf-8

# In[1]:


print("Hello world")


# In[ ]:


# Shift+Enter


# In[3]:


print("Monday 10") 
print("You re on the Skillbox intensiv")
print("DS lecture")


# In[3]:


company = "Skillbox"


# In[4]:


print(company)


# In[6]:


course = "Data Science"
full_name = company+" "+course
print(full_name)


# In[8]:


salary = 100000
tax = 0.13
tax_value = salary*tax
print(salary*tax)


# In[1]:


import pandas as pd


# In[6]:


exchange_rate = pd.read_excelcel("E:/! Data Science/Forecast USD/usd_exchange_rate.xlsx") # Датафрейм = таблица


# In[7]:


exchange_rate


# In[8]:


exchange_rate.curs


# In[9]:


exchange_rate.curs*100 #в копейках


# In[10]:


exchange_rate ["curs kopeyka"] = exchange_rate.curs*100


# In[11]:


exchange_rate


# In[14]:


exchange_rate.curs.plot()


# In[15]:


exchange_rate.curs.describescribe()


# In[ ]:


summ

